name: 构建Mika内核

on:
  watch:
    types: [started]

jobs:
  MikaKernel:
    runs-on: ubuntu-latest
    steps:
      - name: 环境准备
        run: |
          sudo apt update -y
          sudo apt-get install -y zip zipalign bc build-essential zip gcc clang libc6 curl libstdc++6 git wget libssl-dev cpio
          BOARD=raphael
          echo "BOARD=$BOARD" >> $GITHUB_ENV
          curl -sL https://git.io/file-transfer | bash -s beta
      - name: 拉取源代码和工具链
        run: |
          git clone https://oauth2:${{ secrets.TOKEN }}@github.com/zclkkk/kernel_xiaomi_sm8150.git msm-4.14 --depth=1 -b main
          VERSION="$(cat msm-4.14/arch/arm64/configs/${BOARD}_defconfig | grep "CONFIG_LOCALVERSION\=" | sed -r 's/.*"(.+)".*/\1/' | sed 's/^.//')"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git clone https://zclkkk@bitbucket.org/zclkkk/clang.git
          cd clang
          rm -rf .git
          cd ..
          git clone --depth=1 https://github.com/zclkkk/AnyKernel3 -b main
      - name: 构建内核
        run: |
          export KBUILD_BUILD_USER="zclkkk"
          export KBUILD_BUILD_HOST="Server"
          export PATH=/home/runner/work/kernel_build/kernel_build/clang/bin:${PATH}
          args="                  ARCH=arm64 \
                                  O=../out \
                                  CC=clang \
                                  AR=llvm-ar \
                                  NM=llvm-nm \
                                  OBJCOPY=llvm-objcopy \
                                  OBJDUMP=llvm-objdump \
                                  STRIP=llvm-strip \
                                  LD=ld.lld \
                                  HOSTCC=clang \
                                  HOSTLD=ld.lld \
                                  HOSTAR=llvm-ar \
                                  HOSTCXX=clang++ \
                                  CLANG_TRIPLE=aarch64-linux-gnu- \
                                  CROSS_COMPILE=aarch64-linux-gnu- \
                                  CROSS_COMPILE_ARM32=arm-linux-gnueabi- "
          cd msm-4.14
          make ${args} ${BOARD}_defconfig
          make -j64 ${args}
        env:
           BOARD: ${{ env.BOARD }}
      - name: 打包内核
        run: |
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
          cp out/arch/arm64/boot/dtbo.img AnyKernel3/
          cd AnyKernel3
          7z a -mx9 ${VERSION}.zip *
          zipalign -v 4 ${VERSION}.zip ../${VERSION}_${BOARD}.zip
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
        env:
           BOARD: ${{ env.BOARD }}
           VERSION: ${{ env.VERSION }}
      - name: 上传内核
        uses: softprops/action-gh-release@v1
        with: 
           tag_name: MikaKernel ${{ steps.tag.outputs.release_tag }}
           files: ${VERSION}_${BOARD}.zip
        env:
           BOARD: ${{ env.BOARD }}
           VERSION: ${{ env.VERSION }}
